---
- name: Install NGINX From Apt-Get
  become: yes
  apt:
    name: 
      - nginx
      - ssl-cert
    state: present

- name: Disable NGINX Default Virtual Host
  become: yes
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Create NGINX Conf File For Explain
  become: yes
  file:
    path: /etc/nginx/sites-available/explain_proxy.conf
    state: touch

- name: Amend NGINX Conf File
  become: yes
  blockinfile:
      path: /etc/nginx/sites-available/explain_proxy.conf
      marker: ""
      block: |
        server {
          listen 80;
          server_name 51.159.189.172;

          location / {
            return         301 https://$server_name$request_uri;
          }
        }


        server {
          listen 443 ssl http2;

          ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
          ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

          ssl_protocols             TLSv1.2;
          ssl_ciphers               'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:HIGH:!aNULL:!MD5:!eNULL:!EXPORT:!DES:!PSK:!RC4';

          location / {
            proxy_pass http://127.0.0.1:5000;
            proxy_set_header Authorization "";
            proxy_read_timeout 90s;
          }
        }

- name: Link NGINX Explain Reverse Proxy
  become: yes
  file:
    src: "/etc/nginx/sites-available/explain_proxy.conf"
    dest: "/etc/nginx/sites-enabled/explain_proxy.conf"
    state: link

- name: Make Sure NGINX Service Is Running
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
